// Mock Employee Data for Testing
import type { Employee } from '@/types/employee'

export const mockEmployees: Employee[] = [
  {
    id: '1',
    employee_id: 'EMP001',
    name: 'John Smith',
    email: 'john.smith@erp.com',
    phone: '+1234567890',
    department: 'production',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-03-15'),
  },
  {
    id: '2',
    employee_id: 'EMP002',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@erp.com',
    phone: '+1234567891',
    department: 'qc',
    role: 'SUPERVISOR',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-02'),
    updated_at: new Date('2024-03-16'),
  },
  {
    id: '3',
    employee_id: 'EMP003',
    name: 'Mike Davis',
    email: 'mike.davis@erp.com',
    phone: '+1234567892',
    department: 'maintenance',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Night',
    created_at: new Date('2024-01-03'),
    updated_at: new Date('2024-03-10'),
  },
  {
    id: '4',
    employee_id: 'EMP004',
    name: 'Emily Brown',
    email: 'emily.brown@erp.com',
    phone: '+1234567893',
    department: 'admin',
    role: 'ADMIN',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-04'),
    updated_at: new Date('2024-03-18'),
  },
  {
    id: '5',
    employee_id: 'EMP005',
    name: 'David Wilson',
    email: 'david.wilson@erp.com',
    phone: '+1234567894',
    department: 'production',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Night',
    created_at: new Date('2024-01-05'),
    updated_at: new Date('2024-03-12'),
  },
  {
    id: '6',
    employee_id: 'EMP006',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@erp.com',
    phone: '+1234567895',
    department: 'qc',
    role: 'SUPERVISOR',
    status: 'active',
    shift: 'Night',
    created_at: new Date('2024-01-06'),
    updated_at: new Date('2024-03-20'),
  },
  {
    id: '7',
    employee_id: 'EMP007',
    name: 'Robert Taylor',
    email: 'robert.taylor@erp.com',
    phone: '+1234567896',
    department: 'production',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-07'),
    updated_at: new Date('2024-03-14'),
  },
  {
    id: '8',
    employee_id: 'EMP008',
    name: 'Jennifer Martinez',
    email: 'jennifer.martinez@erp.com',
    phone: '+1234567897',
    department: 'qc',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-08'),
    updated_at: new Date('2024-03-16'),
  },
  {
    id: '9',
    employee_id: 'EMP009',
    name: 'James White',
    email: 'james.white@erp.com',
    phone: '+1234567898',
    department: 'maintenance',
    role: 'SUPERVISOR',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-09'),
    updated_at: new Date('2024-03-18'),
  },
  {
    id: '10',
    employee_id: 'EMP010',
    name: 'Maria Garcia',
    email: 'maria.garcia@erp.com',
    phone: '+1234567899',
    department: 'production',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Night',
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-03-19'),
  },
  {
    id: '11',
    employee_id: 'EMP011',
    name: 'William Lee',
    email: 'william.lee@erp.com',
    phone: '+1234567900',
    department: 'production',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-11'),
    updated_at: new Date('2024-03-20'),
  },
  {
    id: '12',
    employee_id: 'EMP012',
    name: 'Patricia Harris',
    email: 'patricia.harris@erp.com',
    phone: '+1234567901',
    department: 'qc',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Night',
    created_at: new Date('2024-01-12'),
    updated_at: new Date('2024-03-21'),
  },
  {
    id: '13',
    employee_id: 'EMP013',
    name: 'Michael Clark',
    email: 'michael.clark@erp.com',
    phone: '+1234567902',
    department: 'maintenance',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Night',
    created_at: new Date('2024-01-13'),
    updated_at: new Date('2024-03-22'),
  },
  {
    id: '14',
    employee_id: 'EMP014',
    name: 'Linda Lewis',
    email: 'linda.lewis@erp.com',
    phone: '+1234567903',
    department: 'admin',
    role: 'ADMIN',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-14'),
    updated_at: new Date('2024-03-23'),
  },
  {
    id: '15',
    employee_id: 'EMP015',
    name: 'Richard Walker',
    email: 'richard.walker@erp.com',
    phone: '+1234567904',
    department: 'production',
    role: 'SUPERVISOR',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-15'),
    updated_at: new Date('2024-03-24'),
  },
  {
    id: '16',
    employee_id: 'EMP016',
    name: 'Barbara Hall',
    email: 'barbara.hall@erp.com',
    phone: '+1234567905',
    department: 'qc',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-16'),
    updated_at: new Date('2024-03-25'),
  },
  {
    id: '17',
    employee_id: 'EMP017',
    name: 'Thomas Allen',
    email: 'thomas.allen@erp.com',
    phone: '+1234567906',
    department: 'production',
    role: 'OPERATOR',
    status: 'on_leave',
    shift: 'Night',
    created_at: new Date('2024-01-17'),
    updated_at: new Date('2024-03-26'),
  },
  {
    id: '18',
    employee_id: 'EMP018',
    name: 'Susan Young',
    email: 'susan.young@erp.com',
    phone: '+1234567907',
    department: 'maintenance',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-18'),
    updated_at: new Date('2024-03-27'),
  },
  {
    id: '19',
    employee_id: 'EMP019',
    name: 'Charles King',
    email: 'charles.king@erp.com',
    phone: '+1234567908',
    department: 'production',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Night',
    created_at: new Date('2024-01-19'),
    updated_at: new Date('2024-03-28'),
  },
  {
    id: '20',
    employee_id: 'EMP020',
    name: 'Jessica Wright',
    email: 'jessica.wright@erp.com',
    phone: '+1234567909',
    department: 'qc',
    role: 'SUPERVISOR',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-20'),
    updated_at: new Date('2024-03-29'),
  },
  {
    id: '21',
    employee_id: 'EMP021',
    name: 'Daniel Lopez',
    email: 'daniel.lopez@erp.com',
    phone: '+1234567910',
    department: 'production',
    role: 'OPERATOR',
    status: 'inactive',
    shift: 'Day',
    created_at: new Date('2024-01-21'),
    updated_at: new Date('2024-03-15'),
  },
  {
    id: '22',
    employee_id: 'EMP022',
    name: 'Karen Scott',
    email: 'karen.scott@erp.com',
    phone: '+1234567911',
    department: 'maintenance',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Night',
    created_at: new Date('2024-01-22'),
    updated_at: new Date('2024-03-16'),
  },
  {
    id: '23',
    employee_id: 'EMP023',
    name: 'Matthew Green',
    email: 'matthew.green@erp.com',
    phone: '+1234567912',
    department: 'production',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-23'),
    updated_at: new Date('2024-03-17'),
  },
  {
    id: '24',
    employee_id: 'EMP024',
    name: 'Nancy Adams',
    email: 'nancy.adams@erp.com',
    phone: '+1234567913',
    department: 'qc',
    role: 'OPERATOR',
    status: 'active',
    shift: 'Night',
    created_at: new Date('2024-01-24'),
    updated_at: new Date('2024-03-18'),
  },
  {
    id: '25',
    employee_id: 'EMP025',
    name: 'Anthony Baker',
    email: 'anthony.baker@erp.com',
    phone: '+1234567914',
    department: 'admin',
    role: 'ADMIN',
    status: 'active',
    shift: 'Day',
    created_at: new Date('2024-01-25'),
    updated_at: new Date('2024-03-19'),
  },
]
