// Mock QC Data for Testing
import type { QualityControl } from '@/types/qc'

export const mockQCRecords: QualityControl[] = [
  {
    id: '1',
    batch_no: 'BATCH-2024-001',
    product_name: 'Widget A',
    quantity_inspected: 100,
    result: 'pass',
    inspector_name: 'Sarah Johnson',
    inspector_id: '2',
    inspection_date: new Date('2024-03-15'),
    notes: 'All parameters within limits. Excellent quality control.',
    created_at: new Date('2024-03-15'),
    updated_at: new Date('2024-03-15'),
  },
  {
    id: '2',
    batch_no: 'BATCH-2024-002',
    product_name: 'Widget B',
    quantity_inspected: 150,
    result: 'pass',
    inspector_name: 'Sarah Johnson',
    inspector_id: '2',
    inspection_date: new Date('2024-03-16'),
    notes: 'Excellent quality. All tests passed with flying colors.',
    created_at: new Date('2024-03-16'),
    updated_at: new Date('2024-03-16'),
  },
  {
    id: '3',
    batch_no: 'BATCH-2024-003',
    product_name: 'Component X',
    quantity_inspected: 75,
    result: 'fail',
    inspector_name: 'Lisa Anderson',
    inspector_id: '6',
    inspection_date: new Date('2024-03-17'),
    defect_reason: 'Minor defects found in surface finish. Some units have scratches and dents. Requires rework before approval.',
    notes: 'Rework required. Contact production team.',
    created_at: new Date('2024-03-17'),
    updated_at: new Date('2024-03-17'),
  },
  {
    id: '4',
    batch_no: 'BATCH-2024-004',
    product_name: 'Widget A',
    quantity_inspected: 200,
    result: 'pending',
    inspector_name: 'Lisa Anderson',
    inspector_id: '6',
    inspection_date: new Date('2024-03-18'),
    notes: 'Inspection in progress. Results pending.',
    created_at: new Date('2024-03-18'),
    updated_at: new Date('2024-03-18'),
  },
  {
    id: '5',
    batch_no: 'BATCH-2024-005',
    product_name: 'Component Y',
    quantity_inspected: 120,
    result: 'pass',
    inspector_name: 'Sarah Johnson',
    inspector_id: '2',
    inspection_date: new Date('2024-03-19'),
    notes: 'Perfect quality. Ready for shipment.',
    created_at: new Date('2024-03-19'),
    updated_at: new Date('2024-03-19'),
  },
  {
    id: '6',
    batch_no: 'BATCH-2024-006',
    product_name: 'Widget C',
    quantity_inspected: 80,
    result: 'fail',
    inspector_name: 'Lisa Anderson',
    inspector_id: '6',
    inspection_date: new Date('2024-03-20'),
    defect_reason: 'Dimensional tolerance issues. 15 units out of specification. Requires recalibration of production equipment.',
    notes: 'Critical issue. Production line needs adjustment.',
    created_at: new Date('2024-03-20'),
    updated_at: new Date('2024-03-20'),
  },
  {
    id: '7',
    batch_no: 'BATCH-2024-007',
    product_name: 'Component Z',
    quantity_inspected: 90,
    result: 'pass',
    inspector_name: 'Sarah Johnson',
    inspector_id: '2',
    inspection_date: new Date('2024-03-21'),
    notes: 'All quality checks passed. Excellent batch.',
    created_at: new Date('2024-03-21'),
    updated_at: new Date('2024-03-21'),
  },
  {
    id: '8',
    batch_no: 'BATCH-2024-008',
    product_name: 'Widget A',
    quantity_inspected: 110,
    result: 'pending',
    inspector_name: 'Lisa Anderson',
    inspector_id: '6',
    inspection_date: new Date('2024-03-22'),
    notes: 'Awaiting final test results.',
    created_at: new Date('2024-03-22'),
    updated_at: new Date('2024-03-22'),
  },
  {
    id: '9',
    batch_no: 'BATCH-2024-009',
    product_name: 'Widget B',
    quantity_inspected: 95,
    result: 'pass',
    inspector_name: 'Sarah Johnson',
    inspector_id: '2',
    inspection_date: new Date('2024-03-23'),
    notes: 'High quality standards maintained. Approved for distribution.',
    created_at: new Date('2024-03-23'),
    updated_at: new Date('2024-03-23'),
  },
  {
    id: '10',
    batch_no: 'BATCH-2024-010',
    product_name: 'Component X',
    quantity_inspected: 130,
    result: 'fail',
    inspector_name: 'Lisa Anderson',
    inspector_id: '6',
    inspection_date: new Date('2024-03-24'),
    defect_reason: 'Material defects detected. 8 units have cracks. Suspected issue with raw material quality. Need to investigate supplier.',
    notes: 'Material quality issue. Contact procurement.',
    created_at: new Date('2024-03-24'),
    updated_at: new Date('2024-03-24'),
  },
  {
    id: '11',
    batch_no: 'BATCH-2024-011',
    product_name: 'Widget D',
    quantity_inspected: 105,
    result: 'pass',
    inspector_name: 'Sarah Johnson',
    inspector_id: '2',
    inspection_date: new Date('2024-03-25'),
    notes: 'Perfect inspection results. All criteria met.',
    created_at: new Date('2024-03-25'),
    updated_at: new Date('2024-03-25'),
  },
  {
    id: '12',
    batch_no: 'BATCH-2024-012',
    product_name: 'Component Y',
    quantity_inspected: 140,
    result: 'pending',
    inspector_name: 'Lisa Anderson',
    inspector_id: '6',
    inspection_date: new Date('2024-03-26'),
    notes: 'Inspection scheduled. Results expected by end of day.',
    created_at: new Date('2024-03-26'),
    updated_at: new Date('2024-03-26'),
  },
  {
    id: '13',
    batch_no: 'BATCH-2024-013',
    product_name: 'Widget A',
    quantity_inspected: 125,
    result: 'pass',
    inspector_name: 'Sarah Johnson',
    inspector_id: '2',
    inspection_date: new Date('2024-03-27'),
    notes: 'Excellent batch quality. Ready for next stage.',
    created_at: new Date('2024-03-27'),
    updated_at: new Date('2024-03-27'),
  },
  {
    id: '14',
    batch_no: 'BATCH-2024-014',
    product_name: 'Widget C',
    quantity_inspected: 85,
    result: 'fail',
    inspector_name: 'Lisa Anderson',
    inspector_id: '6',
    inspection_date: new Date('2024-03-28'),
    defect_reason: 'Color mismatch in 12 units. Paint quality inconsistent. Requires repainting of affected units.',
    notes: 'Cosmetic defect. Non-critical but needs correction.',
    created_at: new Date('2024-03-28'),
    updated_at: new Date('2024-03-28'),
  },
  {
    id: '15',
    batch_no: 'BATCH-2024-015',
    product_name: 'Component Z',
    quantity_inspected: 115,
    result: 'pass',
    inspector_name: 'Sarah Johnson',
    inspector_id: '2',
    inspection_date: new Date('2024-03-29'),
    notes: 'Top quality. Exceeds standards.',
    created_at: new Date('2024-03-29'),
    updated_at: new Date('2024-03-29'),
  },
]
